### PR TITLE
Code to simulate Watts Model

### PR DESCRIPTION
**Pull request by ghost**
I wish to upload a Jupyter notebook with this code and a set of results, but I have no access.

### CODE REVIEW

**Comment by juliohm** [comment]
Hi @buzaku, thank you for the contribution! I don't know what the code is trying to do, could you please confirm the code is yours and maybe give some context? I can help you organize a Jupyter notebook with a better story.

**Comment by ghost** [comment]
Sure, the context was in the workbook, so is missing here. The code is mine. Please find the context from the notebook below.

# Introduction

In this workbook, we demonstrate the usage of LightGraphs to execute diffusion simulations on random graphs. The broad aim is to replicate the results from the influential paper, "A simple model of global cascades on random networks".

Watts, D. J. (2002). A simple model of global cascades on random networks. Proceedings of the National Academy of Sciences, 99(9), 5766-5771.

## Outline

Through this model, Watts demonstrated that a simple threshold rule could be used as a basis to explain global cascades, i.e., events where small initial random shocks spread to a significant proportion of the network. 

One rather surprising result from this study is that even when the average degree of the network is low, a global cascade can be triggered by randomly chosen seeds. This throws a spaner in the usual conception that large scale diffusions on a network are triggered only by "special people", i.e., influencers. 

## Model

A node in a graph is faced with a binary decision - to engage or to not engage (e.g., with new products or discussions with friends). They make this decision based on a simple rule - they compute the fraction of their neighbors that have engaged, compare it with their personal threshold, and engage if the fraction of engaged neighbors exceeds the threshold. In other words, the thought process is on the lines, "If at least 18% of my friends bought the new iPhone, I would want to buy it too".

The execution of this model is random and asynchronous, i.e., each node checks the status of its neighbors in a random order and decides whether to engage or not depending on the fraction of neighbors engaged at that point

**Comment by juliohm** [comment]
Very cool, could you prepare a Jupyter notebook so that we can add it here? The steps are as follows:

1. Fork this repository by pressing the Fork button up there ^
2. On your laptop type:
```
$ git clone URL_FOR_YOUR_FORK
```
Inside of the folder, type:
```
$ git checkout -b mybranch
```
3. Add the notebook next to the others with a clear name such as `Watts-Model.ipynb`.
4. Commit the changes locally by doing:
```
$ git add Watts-Model.ipynb
$ git commit -m "Add Watts model"
```
5. Push the changes to your fork:
```
$ git push URL_FOR_YOUR_FORK
```

After all this process, you should see a message on your fork on GitHub asking to submit a pull request, press on it and I will review the new version. :+1:

I will read the paper, sounds very interesting.

**Comment by ghost** [comment]
Thank you @juliohm . I have sent in the pull request now.

**Pull request closed without merging**
