### PR TITLE
Changed variable types

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by sbromberger** [comment]
`node_status[sample(vertices(G))] = 1`

Assign `true` and `false` instead of `1` and `0` when you change `node_status`.

**Comment by ghost** [comment]
If there are no further changes can this now be incorporated into the list of tutorials?

**Comment by juliohm** [comment]
Hi @buzaku , could you please confirm this is the histogram you expect to see?

screenshot from 2018-01-05 12-09-17

Also, could you please clean up the last cells of the notebook? There is an empty cell at the end and other cells that I think could merged like the one with a simple call to `srand()`, maybe it could be merged with the first cell loading the packages? Also, what about using a different Plots.jl backend like GR so that the plots show up online on Git and nbviewer?

**Comment by juliohm** [comment]
Just to make sure you know how to make these changes, the only thing you need to do is make the changes locally on your laptop, then add the changes, commit and push again. GitHub will update the pull request automatically:

```
$ git add SimulatingWattsModel.ipynb
$ git commit -m "fix empty cells and other things"
$ git push URL_FOR_YOUR_FORK
```

**Comment by ghost** [comment]
@juliohm Yes, This is precisely the graph which shows the phase transition mentioned in the original paper. I will change the plotting back end and update the notebook. And yes, your instructions on git have been most helpful! :)

**Comment by juliohm** [comment]
It would also be nice if you could add cell at the top installing dependencies like I did in other notebooks, so that users can just hit enter and get anything needed to reproduce the work.

**Comment by juliohm** [comment]
Thank you again @buzaku for the follow up fixes! Nice contribution.

I will fix some other small details on the master branch regarding the plot commands. :+1:

**Comment by juliohm** [comment]
Added the updates and a link to the README: http://nbviewer.jupyter.org/github/JuliaGraphs/JuliaGraphsTutorials/blob/master/Watts-Model.ipynb

**Pull request merged**
