### PR TITLE
Is there a Tipping Point?

### PR DESCRIPTION
**Pull request by ghost**
Added a workbook analyzing The Tipping Point

### CODE REVIEW

**Comment by juliohm** [comment]
Thanks @buzaku! Awesome, I will review it soon I find some time, thanks for all the contributions, very welcome. :)

**Comment by ghost** [comment]
I have been immensely benefited by @sbromberger's solution to an earlier [issue](https://github.com/JuliaGraphs/LightGraphs.jl/issues/769) I faced. The least I can do is to contribute back at my skill level!

**Comment by juliohm** [comment]
Hi @buzaku these notebooks are awesome, thanks. There is only one issue with the current pull request, it seems it contains the same changes already incorporated in a previous pull request? I suppose the change you are trying to make only regards the new notebook TheTippingPoint.ipynb, correct? The current pull requests tries to add again the other notebook on Watts model.

Could you please confirm this is your intention, and perhaps resubmit a clean pull request?

**Comment by ghost** [comment]
Yes, the intention is to add only the new notebook (TheTippingPoint.ipnyb). Sorry, I am very new to git and hence this confusion. I will try to submit a new pull request shortly with only this notebook.

**Comment by juliohm** [comment]
No worries at all, version control is complicated, it takes time to get used to it. :)

Looking forward to your new pull request, I want to find time to learn more about these notebooks you are uploading!

**Pull request closed without merging**
